### ISSUE TITLE
FAB btn: Attr for fixed position 

### ISSUE THREAD

**Issue by Doehl** [driftyco/ionic2#898]
I could be an idéer to add an attribute like ```fab-fixed``` for the fab button to be fixed on the screen.
To be used with the ```fab-[posistion]``` attr's.

```css
[fab-fixed] {
    position: fixed;
}
```

I will create a pull-request with the css change.
